const statisticsActionType = {
    FETCH_STATISTICS_START: 'FETCH_STATISTICS_START',
    FETCH_STATISTICS_SUCCESS: 'FETCH_STATISTICS_SUCCESS',
    FETCH_STATISTICS_FAILURE: 'FETCH_STATISTICS_FAILURE'
}

export default statisticsActionType