const playerActionType = {
    FETCH_PLAYERS_START: 'FETCH_PLAYERS_START',
    FETCH_PLAYERS_SUCCESS: 'FETCH_PLAYERS_SUCCESS',
    FETCH_PLAYERS_FAILURE: 'FETCH_PLAYERS_FAILURE'
}

export default playerActionType