const gameActionType = {
    FETCH_GAME_START: 'FETCH_GAME_START',
    FETCH_GAME_SUCCESS: 'FETCH_GAME_SUCCESS',
    FETCH_GAME_FAILURE: 'FETCH_GAME_FAILURE',
    FILTER_BY_COPAMX: 'FILTER_BY_COPAMX',
    FILTER_BY_ASCENSOMX: 'FILTER_BY_ASCENSOMX'
}

export default gameActionType